# -*- coding: utf-8 -*-
"""
Banc de preguntes de L'AUTOAVALUACIÓ DEL WEB.

10 preguntes per unitat. No puntuen: serveixen perquè l'alumnat comprove si ha
entés la unitat abans del qüestionari d'Aules. Es publiquen a
docs/assets/quizzes/ i les mostra el web.

Les preguntes avaluables d'Aules estan en scripts/banc_aules.py i han de ser
DIFERENTS d'aquestes.

Format de cada pregunta:
    ("mc", "Enunciat", [
        ("Opció correcta", "Retroalimentació quan s'encerta"),
        ("Distractor",     "Per què no és correcta"),
        ...
    ])

La PRIMERA opció sempre és la correcta. El generador ja les barreja al web i
afig automàticament l'opció «No ho sé» al final.

Després de qualsevol canvi:  python scripts/genera.py
"""

UNITATS = {
    "u01": {
        "titol": "U01. Digitalització en els sistemes productius",
        "ra": "RA1",
        "preguntes": [
            ("mc",
                "Tarongina escaneja tots els albarans d'entrada de fruita i els guarda en PDF en una carpeta del servidor. Com es diu això?",
                [
                    ("Digitització", "Només canvia el suport: el paper passa a ser un fitxer, però el procés de treball continua igual."),
                    ("Transformació digital", "No. La transformació digital canvia el model de negoci i la manera de treballar, no només el format dels documents."),
                    ("Convergència IT-OT", "No. La convergència IT-OT és la integració entre els sistemes de negoci i els de planta."),
                    ("Automatització industrial", "No. Ací no hi ha cap màquina ni cap procés productiu automatitzat."),
                ],
            ),
            ("mc",
                "Quina d'aquestes afirmacions descriu millor la transformació digital?",
                [
                    ("Un canvi integral de processos, cultura i model de negoci recolzat en la tecnologia", "Exacte. Va molt més enllà d'incorporar eines: canvia com treballa i com guanya diners l'organització."),
                    ("Comprar equipament informàtic més modern per a tota l'empresa", "No. Renovar maquinari no canvia per si sol la manera de treballar."),
                    ("Passar tots els documents de paper a format digital", "Això és digitització, el primer nivell i el més superficial."),
                    ("Contractar una empresa externa que gestione la informàtica", "No. Externalitzar el suport tècnic no transforma el negoci."),
                ],
            ),
            ("mc",
                "La calibradora òptica que classifica la fruita per mida al magatzem de Tarongina pertany a...",
                [
                    ("L'entorn OT", "Correcte. L'OT controla i supervisa processos i màquines del món físic."),
                    ("L'entorn IT", "No. L'IT gestiona la informació del negoci: dades, aplicacions i comunicacions."),
                    ("Cap dels dos: és només maquinària", "No. Qualsevol màquina amb control automatitzat forma part de l'entorn OT."),
                    ("Tots dos, perquè és una màquina amb programari", "Que tinga programari no la fa IT: el criteri és què controla, i ací controla un procés físic."),
                ],
            ),
            ("mc",
                "Quina és la prioritat principal en un entorn OT?",
                [
                    ("La disponibilitat del procés i la seguretat de les persones", "Correcte. Una parada de producció o un accident són molt més greus que una filtració puntual de dades."),
                    ("La confidencialitat de les dades", "Eixa és la prioritat típica de l'entorn IT."),
                    ("Renovar els equips cada tres anys", "Al contrari: en OT els equips solen durar entre deu i vint anys."),
                    ("Aplicar actualitzacions automàtiques cada setmana", "No. En OT actualitzar sovint implica parar la producció, així que es fa molt poques vegades."),
                ],
            ),
            ("mc",
                "Quin d'aquests departaments constitueix típicament un entorn IT?",
                [
                    ("El departament d'administració i comptabilitat", "Correcte. Treballa amb informació del negoci: facturació, ERP i comptabilitat."),
                    ("El magatzem de confecció de fruita", "No. El magatzem és un entorn OT: màquines i processos físics."),
                    ("El servei de reg de les finques", "No. Els sensors i els programadors de reg són entorn OT."),
                    ("La cambra frigorífica", "No. És un equip de control de procés físic, per tant OT."),
                ],
            ),
            ("mc",
                "Quina d'aquestes tecnologies és pròpia de la digitalització en planta?",
                [
                    ("Sensors IoT i autòmats programables (PLC)", "Correcte. Són tecnologies que actuen directament sobre el procés productiu."),
                    ("Un sistema CRM de gestió de clients", "No. El CRM és digitalització en negoci."),
                    ("La facturació electrònica", "No. És digitalització en negoci, de l'àrea administrativa."),
                    ("Un quadre de comandament de direcció (BI)", "No. El BI dona suport a la presa de decisions de negoci."),
                ],
            ),
            ("mc",
                "Per què és important connectar els entorns IT i OT d'una empresa?",
                [
                    ("Perquè la informació puja i baixa sense copiar-se a mà, i les decisions es prenen amb dades reals", "Correcte. Cada còpia manual és un retard i una font d'errors."),
                    ("Perquè així es pot fer servir el mateix antivirus en tota l'empresa", "No. Unificar l'antivirus no és el motiu, i de fet connectar-ho tot també comporta riscos nous."),
                    ("Perquè permet estalviar en llicències de programari", "No és el motiu principal: el valor està en el flux d'informació."),
                    ("Perquè la llei obliga les empreses industrials a fer-ho", "No existeix cap obligació legal general en aquest sentit."),
                ],
            ),
            ("mc",
                "A Tarongina, la calibradora imprimeix un tiquet que després algú tecleja en l'ordinador de l'oficina. Quin problema evidencia?",
                [
                    ("Manca de connexió entre l'entorn OT i l'entorn IT", "Exacte. La dada existeix en digital, es converteix en paper i torna a teclejar-se: és el símptoma clàssic de dos móns que no es parlen."),
                    ("Que la calibradora està mal configurada", "No. La màquina fa la seua faena correctament; el que falta és la integració."),
                    ("Que el personal d'oficina no té formació suficient", "No. El problema és de disseny del sistema, no de les persones."),
                    ("Que cal substituir l'ERP per un de més modern", "No necessàriament: l'ERP pot ser adequat i faltar només la integració."),
                ],
            ),
            ("mc",
                "Quin és un dels principals avantatges de digitalitzar una empresa d'extrem a extrem?",
                [
                    ("Traçabilitat: se sap on és cada producte i d'on ve en qualsevol moment", "Correcte. És especialment valuós en el sector agroalimentari i per a l'exportació."),
                    ("Que desapareix la necessitat de personal qualificat", "Al contrari: sol requerir perfils més qualificats i formació contínua."),
                    ("Que s'elimina completament el risc de ciberatacs", "Just al revés: connectar-ho tot amplia la superfície d'atac."),
                    ("Que la inversió inicial és sempre molt baixa", "No. La inversió inicial acostuma a ser un dels principals obstacles."),
                ],
            ),
            ("mc",
                "Quin d'aquests NO és un inconvenient habitual de la transformació digital?",
                [
                    ("La millora en la presa de decisions basada en dades", "Efectivament, això és un avantatge, no un inconvenient."),
                    ("La resistència al canvi per part de la plantilla", "Sí que ho és: és un dels obstacles més citats en qualsevol projecte."),
                    ("La inversió inicial i els sistemes antics difícils de substituir", "Sí que ho és: el llegat tecnològic frena molts projectes."),
                    ("Els nous riscos de ciberseguretat en connectar la planta", "Sí que ho és: en connectar l'OT s'obrin vies d'atac que abans no existien."),
                ],
            ),
        ],
    },
    "u02": {
        "titol": "U02. Tecnologies habilitadores digitals",
        "ra": "RA2",
        "preguntes": [
            ("mc",
                "Què són les tecnologies habilitadores digitals (THD)?",
                [
                    ("El conjunt de tecnologies clau que fan possible la transformació digital de les empreses", "Correcte. Són la infraestructura i les capacitats sobre les quals es construeix la digitalització."),
                    ("Les aplicacions d'ofimàtica que utilitza el personal d'oficina", "No. L'ofimàtica és una eina de treball, no una tecnologia habilitadora."),
                    ("Els programes de disseny assistit per ordinador", "No. És una aplicació concreta, no una família de tecnologies transformadores."),
                    ("Les normes legals que regulen la digitalització de les empreses", "No. La normativa acompanya el procés, però no és una tecnologia."),
                ],
            ),
            ("mc",
                "Tarongina vol que un client alemany puga comprovar de quina finca ve cada caixa i que aquesta informació no es puga alterar. Quina THD encaixa millor?",
                [
                    ("Blockchain", "Correcte. És un registre distribuït en què les dades, una vegada escrites, són molt difícils de modificar."),
                    ("Realitat augmentada", "No. La RA superposa informació digital sobre el món real, però no garanteix la integritat del registre."),
                    ("Impressió 3D", "No. La fabricació additiva no té relació amb la traçabilitat documental."),
                    ("Robòtica col·laborativa", "No. Els cobots treballen al costat de les persones, però no registren traçabilitat."),
                ],
            ),
            ("mc",
                "Què és un bessó digital (digital twin)?",
                [
                    ("Una rèplica virtual d'un objecte o procés real que s'alimenta de dades i permet simular-lo", "Correcte. Permet provar canvis i anticipar problemes sense tocar el sistema real."),
                    ("Una còpia de seguretat duplicada d'un servidor", "No. Una còpia de seguretat no simula el comportament del sistema."),
                    ("Un segon compte d'usuari per a la mateixa persona", "No. No té cap relació amb la gestió d'identitats."),
                    ("Una màquina idèntica de reserva per si la principal s'avaria", "No. El bessó digital és virtual, no una màquina física."),
                ],
            ),
            ("mc",
                "Quina característica defineix millor les xarxes 5G com a tecnologia habilitadora?",
                [
                    ("Alta velocitat, baixa latència i molts dispositius connectats alhora", "Correcte. Per això són la base de connectivitat de l'IoT industrial."),
                    ("Que substitueixen completament les xarxes de fibra òptica", "No. Es complementen amb la fibra, no la substitueixen."),
                    ("Que garanteixen la seguretat de les dades per si mateixes", "No. La seguretat continua requerint mesures específiques."),
                    ("Que només funcionen en entorns industrials tancats", "No. El 5G és una tecnologia de xarxa mòbil d'ús general."),
                ],
            ),
            ("mc",
                "Quina diferència hi ha entre l'economia lineal i l'economia circular?",
                [
                    ("La lineal produeix, consumeix i descarta; la circular busca reduir residus i reaprofitar recursos", "Correcte. La circular tanca el cicle en lloc d'acabar en l'abocador."),
                    ("La lineal és més moderna que la circular", "No. L'economia circular és precisament el model alternatiu i més recent."),
                    ("La circular només s'aplica a empreses de reciclatge", "No. És un model aplicable a qualsevol sector productiu."),
                    ("No hi ha diferència real, són sinònims", "No. Són models antagònics en el plantejament i en el tractament dels residus."),
                ],
            ),
            ("mc",
                "Tarongina lloga la maquinària de reg en lloc de comprar-la i paga per hores d'ús. A quin model de negoci sostenible correspon?",
                [
                    ("Producte com a servei", "Correcte. Es reemplaça l'adquisició del producte per la prestació del servei que aquest ofereix."),
                    ("Simbiosi industrial", "No. La simbiosi industrial és l'intercanvi de fluxos entre empreses diferents."),
                    ("Ecodisseny", "No. L'ecodisseny actua en la fase de disseny del producte."),
                    ("Producció JIT", "No. El JIT consisteix a produir just en el moment en què cal."),
                ],
            ),
            ("mc",
                "Tarongina cedeix la pela i el destrí de la taronja a una empresa veïna que en fabrica pinso. Com s'anomena aquest model?",
                [
                    ("Simbiosi industrial", "Correcte. Els residus d'una empresa es converteixen en matèria primera d'una altra."),
                    ("Extensió de la vida del producte", "No. Aquest model busca allargar la vida útil d'un producte, no aprofitar-ne els residus."),
                    ("Producció JIT", "No. El JIT es refereix al moment de producció, no a l'aprofitament de residus."),
                    ("Obsolescència programada", "No. Precisament és el contrari del que busca la sostenibilitat."),
                ],
            ),
            ("mc",
                "Què caracteritza la indústria 5.0 respecte de la indústria 4.0?",
                [
                    ("Posa la persona treballadora en el centre del procés, amb un ús intensiu de les THD", "Correcte. La 4.0 se centrava a digitalitzar i automatitzar; la 5.0 hi afegeix la dimensió humana i sostenible."),
                    ("Elimina completament la intervenció humana en la producció", "No. Justament al contrari: recupera el paper de les persones."),
                    ("Recupera els processos manuals de la indústria tradicional", "No. La indústria 5.0 no és una tornada arrere tecnològica."),
                    ("És el nom que rep l'automatització amb energia elèctrica", "Això correspon a la segona revolució industrial."),
                ],
            ),
            ("mc",
                "Quin d'aquests és un mercat nou generat per l'IoT?",
                [
                    ("L'agricultura intel·ligent, amb sensors que monitoren cultius i clima", "Correcte. És, a més, el més proper al cas de Tarongina."),
                    ("Els contractes intel·ligents en cadenes de blocs", "No. Els contractes intel·ligents són un mercat generat pel blockchain."),
                    ("La formació immersiva amb ulleres de realitat virtual", "No. Correspon al mercat de la RV."),
                    ("La creació de pròtesis mèdiques personalitzades", "No. És un mercat generat per la impressió 3D."),
                ],
            ),
            ("mc",
                "La cooperativa vol reduir l'ús d'aigua i de productes fitosanitaris. Quina combinació de THD hi ajudaria més directament?",
                [
                    ("Sensors IoT al camp i analítica de dades per a decidir quan i quant regar", "Correcte. Mesurar primer i decidir amb dades és la via per a optimitzar recursos."),
                    ("Impressió 3D i realitat virtual", "No tenen relació directa amb l'optimització del reg."),
                    ("Blockchain i contractes intel·ligents", "Serveixen per a la traçabilitat i la confiança, no per a estalviar aigua."),
                    ("Robòtica col·laborativa i xarxes 5G", "El 5G dona connectivitat, però per si sol no optimitza el consum."),
                ],
            ),
        ],
    },
    "u03": {
        "titol": "U03. Intel·ligència artificial",
        "ra": "RA4",
        "preguntes": [
            ("mc",
                "Quina d'aquestes tasques és un exemple clar d'intel·ligència artificial?",
                [
                    ("Detectar taronges amb defectes a partir de les imatges d'una càmera", "Correcte. És visió artificial: un model que ha aprés a reconéixer patrons en imatges."),
                    ("Programar un correu perquè s'envie cada dilluns a les 9 h", "No. És una automatització amb una regla fixa, sense aprenentatge."),
                    ("Guardar un full de càlcul en el núvol", "No. És emmagatzematge, no intel·ligència artificial."),
                    ("Ordenar alfabèticament una llista de clients", "No. És una operació determinista de tota la vida."),
                ],
            ),
            ("mc",
                "Què és el machine learning?",
                [
                    ("Una tècnica que permet a un sistema millorar a partir de dades, sense programar cada cas", "Correcte. El model aprén dels exemples en lloc de seguir regles escrites a mà."),
                    ("Un llenguatge de programació especialitzat en IA", "No. El machine learning és una disciplina, no un llenguatge."),
                    ("El manteniment automàtic de la maquinària industrial", "No. Això és manteniment predictiu, que pot fer servir machine learning però no és el mateix."),
                    ("Un tipus de robot que aprén a moure's sol", "No. És un concepte de programari, no una categoria de robots."),
                ],
            ),
            ("mc",
                "Quina relació hi ha entre la IA i el Big Data?",
                [
                    ("La IA necessita grans volums de dades de qualitat per a entrenar els seus models", "Correcte. Sense dades no hi ha analítica, i sense analítica no hi ha IA útil."),
                    ("Són el mateix concepte amb dos noms diferents", "No. El Big Data són les dades i la seua gestió; la IA és el que se'n fa després."),
                    ("La IA serveix per a reduir la quantitat de dades que guarda l'empresa", "No és eixa la seua finalitat."),
                    ("El Big Data va substituir la IA fa uns anys", "No. Són disciplines complementàries, no successives."),
                ],
            ),
            ("mc",
                "Quin llenguatge de programació predomina en projectes d'intel·ligència artificial i ciència de dades?",
                [
                    ("Python", "Correcte. Concentra les biblioteques més utilitzades: scikit-learn, TensorFlow o PyTorch."),
                    ("HTML", "No. HTML és un llenguatge de marques per a estructurar pàgines web."),
                    ("SQL", "SQL és fonamental per a consultar dades, però no és el llenguatge en què s'entrenen els models."),
                    ("CSS", "No. CSS serveix per a donar estil a les pàgines web."),
                ],
            ),
            ("mc",
                "Tarongina vol preveure quantes tones collirà aquesta campanya per a organitzar el magatzem. Quin tipus de problema d'IA és?",
                [
                    ("Un problema de predicció a partir de dades històriques i meteorològiques", "Correcte. És un cas típic d'analítica predictiva."),
                    ("Un problema de visió artificial", "No. La visió artificial treballa amb imatges, no amb sèries de dades històriques."),
                    ("Un problema de processament de llenguatge natural", "No. Ací no hi intervé cap text ni cap conversa."),
                    ("Un problema que la IA no pot abordar", "Al contrari: la predicció de demanda i producció és un dels usos més estesos."),
                ],
            ),
            ("mc",
                "Què és la visió artificial?",
                [
                    ("La capacitat d'un sistema d'interpretar imatges o vídeo per a reconéixer objectes o defectes", "Correcte. Al magatzem permetria detectar fruita amb taques, cops o mida incorrecta."),
                    ("La possibilitat de veure les càmeres de seguretat des del mòbil", "No. Visualitzar imatges no és interpretar-les automàticament."),
                    ("Un sistema de realitat virtual per a formar operaris", "No. Això és RV, una tecnologia diferent."),
                    ("La digitalització de fotografies antigues de l'empresa", "No. Escanejar imatges és digitització."),
                ],
            ),
            ("mc",
                "Quin d'aquests sectors té actualment una implantació més rellevant de la IA?",
                [
                    ("La banca, per a detectar fraus en transaccions", "Correcte. És un dels casos d'ús més consolidats i rendibles."),
                    ("L'artesania tradicional", "No és un sector amb implantació destacada d'IA."),
                    ("La restauració familiar de barri", "No és dels sectors on la IA té una implantació més rellevant."),
                    ("El comerç ambulant", "No és un sector amb una implantació significativa d'IA."),
                ],
            ),
            ("mc",
                "Quin risc cal tindre en compte quan s'automatitza una decisió amb IA?",
                [
                    ("Que el model reproduïsca els biaixos presents en les dades amb què s'ha entrenat", "Correcte. Si les dades històriques estan esbiaixades, el model aprendrà eixe biaix i el repetirà."),
                    ("Que el model necessite connexió a internet per a funcionar", "És una limitació tècnica menor, i no sempre certa."),
                    ("Que els models d'IA no es puguen programar en Python", "No és cert: Python és precisament el llenguatge dominant."),
                    ("Que la IA sempre siga més cara que fer-ho a mà", "No és cert de manera general; depén del cas."),
                ],
            ),
            ("mc",
                "Com pot influir la IA en el perfil professional de la informàtica?",
                [
                    ("Apareixen tasques noves d'integració de models, tractament de dades i validació de resultats", "Correcte. El perfil evoluciona cap a integrar, avaluar i mantindre sistemes intel·ligents."),
                    ("Desapareixerà la necessitat de programar res", "No. Continua sent imprescindible integrar, provar i mantindre els sistemes."),
                    ("Afecta només les grans empreses tecnològiques", "No. Cada vegada més pimes incorporen serveis d'IA."),
                    ("Només afecta el personal de màrqueting", "No. Afecta de ple els perfils tècnics."),
                ],
            ),
            ("mc",
                "Un assistent conversacional que atén els dubtes de les persones sòcies de la cooperativa és un exemple de...",
                [
                    ("Processament del llenguatge natural", "Correcte. El sistema interpreta i genera text en llenguatge humà."),
                    ("Manteniment predictiu", "No. El manteniment predictiu anticipa avaries en equips."),
                    ("Bessó digital", "No. Un bessó digital replica un objecte o procés físic."),
                    ("Automatització robòtica de planta", "No. Ací no hi ha cap procés físic implicat."),
                ],
            ),
        ],
    },
    "u04": {
        "titol": "U04. Big Data i dades",
        "ra": "RA5",
        "preguntes": [
            ("mc",
                "Quina és la diferència entre dada i informació?",
                [
                    ("La informació és el resultat de processar les dades i donar-los context", "Correcte. «23» és una dada; «hui fa 23 °C a la finca del Pla» ja és informació."),
                    ("Són sinònims: només canvia la paraula", "No. Una dada aïllada no significa res fins que es processa i es contextualitza."),
                    ("Una dada sempre és més valuosa que la informació", "No. El valor per a decidir està en la informació."),
                    ("La informació sempre és numèrica i la dada no", "No. Ni una cosa ni l'altra: el format no és el criteri."),
                ],
            ),
            ("mc",
                "Quines són les característiques clàssiques que defineixen el Big Data?",
                [
                    ("Volum, velocitat i varietat", "Correcte. Són les tres «V» clàssiques, a les quals sovint s'afegeixen la veracitat i el valor."),
                    ("Velocitat, seguretat i preu", "No. La seguretat i el preu són consideracions importants, però no defineixen el concepte."),
                    ("Volum, vigilància i validesa", "No. No és la formulació habitual del concepte."),
                    ("Varietat, visibilitat i virtualització", "No. La virtualització pertany a un altre àmbit."),
                ],
            ),
            ("mc",
                "Quin d'aquests passos NO forma part del cicle de vida de la dada?",
                [
                    ("La impressió obligatòria en paper per a arxivar-la", "Efectivament, no forma part del cicle: és, de fet, un pas cap arrere."),
                    ("La captura o recollida de la dada", "Sí que en forma part: és el primer pas del cicle."),
                    ("L'emmagatzematge i el processament", "Sí que en formen part."),
                    ("L'eliminació o l'arxivat quan ja no és necessària", "Sí que en forma part: tota dada té un final de vida previst."),
                ],
            ),
            ("mc",
                "Una empresa guarda les còpies de seguretat en el mateix servidor on estan les dades originals. Per què és un problema greu?",
                [
                    ("Perquè un incident que afecte el servidor destrueix alhora les dades i la còpia", "Correcte. Una còpia que cau amb l'original no és realment una còpia de seguretat."),
                    ("Perquè ocupa massa espai en disc", "L'espai és un problema menor comparat amb el risc real."),
                    ("Perquè les còpies de seguretat estan prohibides per llei", "No és cert: la normativa n'exigeix, no les prohibeix."),
                    ("Perquè alenteix la xarxa de l'oficina", "Pot passar, però no és el problema de fons."),
                ],
            ),
            ("mc",
                "Quina norma regula la protecció de les dades personals a la Unió Europea?",
                [
                    ("El Reglament general de protecció de dades (RGPD)", "Correcte. A l'Estat espanyol es complementa amb la LOPDGDD."),
                    ("La norma ISO 9001", "No. La ISO 9001 tracta de la gestió de la qualitat."),
                    ("La Llei de propietat intel·lectual", "No. Regula els drets d'autor, no les dades personals."),
                    ("L'Estatut dels treballadors", "No. Regula les relacions laborals."),
                ],
            ),
            ("mc",
                "Quines dades de Tarongina són dades personals i, per tant, estan subjectes al RGPD?",
                [
                    ("El nom, el DNI i el compte bancari de les persones sòcies", "Correcte. Identifiquen persones físiques i requereixen protecció especial."),
                    ("La temperatura registrada per les cambres frigorífiques", "No. No permet identificar cap persona."),
                    ("El calibre mitjà de la fruita d'una partida", "No. És una dada de producte, no personal."),
                    ("Les tones de taronja collides per finca", "Només ho serien si permeteren identificar una persona concreta."),
                ],
            ),
            ("mc",
                "Quin és l'ordre correcte de les etapes típiques d'un projecte de ciència de dades?",
                [
                    ("Recollida, neteja, anàlisi, modelatge i visualització dels resultats", "Correcte. La neteja sol ser la fase més llarga i la més oblidada."),
                    ("Modelatge, recollida, visualització i neteja", "No. No es pot modelar abans de tindre i netejar les dades."),
                    ("Visualització, anàlisi, recollida i neteja", "No. La visualització és el final del procés, no el principi."),
                    ("Neteja, visualització, recollida i modelatge", "No. La recollida sempre va primer."),
                ],
            ),
            ("mc",
                "Per què es diu que les dades són un actiu estratègic de l'empresa?",
                [
                    ("Perquè permeten prendre decisions fonamentades i generen avantatge competitiu", "Correcte. Una empresa que mesura pot millorar; una que no mesura, decideix a cegues."),
                    ("Perquè es poden vendre lliurement a tercers", "No. La venda de dades està fortament limitada per la normativa."),
                    ("Perquè ocupen espai i cal pagar per emmagatzemar-les", "Això és un cost, no el motiu pel qual són un actiu."),
                    ("Perquè la llei obliga a conservar-les indefinidament", "No. La normativa fixa terminis i el principi de minimització."),
                ],
            ),
            ("mc",
                "Què és un KPI?",
                [
                    ("Un indicador clau que mesura el grau de compliment d'un objectiu", "Correcte. Per exemple: percentatge de comandes servides a temps."),
                    ("Un tipus de base de dades distribuïda", "No. No té relació amb l'emmagatzematge."),
                    ("Un protocol de comunicació entre màquines", "No. No és una tecnologia de comunicació."),
                    ("Un programa de còpies de seguretat", "No. No té cap relació amb les còpies."),
                ],
            ),
            ("mc",
                "Quina mesura de seguretat protegiria millor Tarongina davant d'un segrest de dades (ransomware)?",
                [
                    ("Còpies de seguretat fora de línia i provades periòdicament", "Correcte. Si la còpia està desconnectada i s'ha comprovat que es pot restaurar, l'impacte es redueix molt."),
                    ("Canviar la contrasenya del wifi cada mes", "Ajuda, però no protegeix davant d'un xifratge de fitxers."),
                    ("Instal·lar només un antivirus gratuït", "Insuficient: cap antivirus detecta el cent per cent de les amenaces."),
                    ("Guardar-ho tot en un únic servidor ben protegit", "Al contrari: concentrar-ho tot en un punt augmenta el risc."),
                ],
            ),
        ],
    },
    "u05": {
        "titol": "U05. Computació en el núvol",
        "ra": "RA3",
        "preguntes": [
            ("mc",
                "Tarongina utilitza Microsoft 365 sense instal·lar ni mantindre cap servidor. Quin model de servei és?",
                [
                    ("SaaS (programari com a servei)", "Correcte. L'empresa només fa servir l'aplicació; el proveïdor s'encarrega de tota la resta."),
                    ("IaaS (infraestructura com a servei)", "No. En IaaS l'empresa lloga màquines virtuals i les gestiona ella mateixa."),
                    ("PaaS (plataforma com a servei)", "No. El PaaS ofereix una plataforma per a desplegar aplicacions pròpies."),
                    ("Núvol privat", "No. El model de servei i el de desplegament són coses diferents."),
                ],
            ),
            ("mc",
                "Quin model de núvol contracta una empresa que lloga màquines virtuals i hi instal·la el sistema operatiu i les aplicacions que vol?",
                [
                    ("IaaS", "Correcte. Es lloga la infraestructura i el client gestiona tot el que hi ha damunt."),
                    ("SaaS", "No. En SaaS el client no gestiona ni el sistema operatiu ni l'aplicació."),
                    ("PaaS", "No. En PaaS el proveïdor també gestiona el sistema operatiu i l'entorn d'execució."),
                    ("Edge computing", "No. L'edge és una arquitectura de processament, no un model de servei."),
                ],
            ),
            ("mc",
                "Què és l'edge computing?",
                [
                    ("Processar les dades a prop d'on es generen, al dispositiu o al costat del procés", "Correcte. Redueix la latència i la quantitat de dades que cal enviar al núvol."),
                    ("Processar-ho tot en un centre de dades remot", "No. Això és el model de núvol centralitzat."),
                    ("Esborrar les dades antigues per a estalviar espai", "No. L'edge no consisteix a esborrar res."),
                    ("Xifrar les dades abans d'enviar-les", "No. El xifratge és una mesura de seguretat, no una arquitectura."),
                ],
            ),
            ("mc",
                "Per què a Tarongina interessa processar en l'edge les dades del control de temperatura de les cambres?",
                [
                    ("Perquè cal reaccionar a l'instant encara que es perda la connexió a internet", "Correcte. La seguretat alimentària no pot dependre que la línia funcione."),
                    ("Perquè és sempre més barat que el núvol", "No necessàriament: cada arquitectura té els seus costos."),
                    ("Perquè el núvol no admet dades de temperatura", "No és cert: el núvol admet qualsevol tipus de dada."),
                    ("Perquè la llei prohibeix enviar dades industrials al núvol", "No existeix cap prohibició d'aquest tipus."),
                ],
            ),
            ("mc",
                "Com se situen els conceptes de fog i mist respecte de l'edge i el núvol?",
                [
                    ("Són capes intermèdies entre els dispositius i el núvol, amb el mist molt prop del sensor", "Correcte. De més prop a més lluny: mist, edge, fog i núvol."),
                    ("Són sinònims exactes de núvol públic", "No. Designen capes de processament diferents."),
                    ("Són models de facturació dels proveïdors de núvol", "No. No tenen relació amb la facturació."),
                    ("Són protocols de xifratge per a l'IoT", "No. No són protocols de seguretat."),
                ],
            ),
            ("mc",
                "Quin és un dels principals avantatges del núvol per a una pime com Tarongina?",
                [
                    ("L'escalabilitat: es paga pel que es fa servir i es creix sense comprar servidors", "Correcte. Molt útil quan la campanya concentra el pic de feina en pocs mesos."),
                    ("Que elimina totalment la necessitat de connexió a internet", "Al contrari: la dependència de la connexió augmenta."),
                    ("Que les dades deixen d'estar subjectes al RGPD", "No. La responsabilitat sobre les dades continua sent de l'empresa."),
                    ("Que la seguretat passa a ser responsabilitat exclusiva del proveïdor", "No. Hi ha un model de responsabilitat compartida."),
                ],
            ),
            ("mc",
                "Quin és un inconvenient real de migrar al núvol?",
                [
                    ("La dependència del proveïdor i la dificultat de canviar-ne més endavant", "Correcte. És el que es coneix com a vendor lock-in."),
                    ("Que sempre resulta més car que tindre servidors propis", "Depén del cas: en molts escenaris és més barat."),
                    ("Que no permet fer còpies de seguretat", "No és cert: les còpies són un dels serveis bàsics."),
                    ("Que obliga a canviar tots els ordinadors de l'empresa", "No és cert."),
                ],
            ),
            ("mc",
                "Què és el núvol híbrid?",
                [
                    ("Una combinació de recursos propis i de núvol públic que treballen conjuntament", "Correcte. Permet mantindre en casa allò més sensible i portar la resta al núvol."),
                    ("Un núvol que només funciona de nit", "No té cap sentit tècnic."),
                    ("Un servei que barreja diferents sistemes operatius", "No. La barreja no és de sistemes operatius, sinó de models de desplegament."),
                    ("Un núvol compartit entre empreses de la competència", "Això s'acostaria més al concepte de núvol comunitari."),
                ],
            ),
            ("mc",
                "Quina funció NO és pròpia del núvol?",
                [
                    ("Garantir que el personal de l'empresa tinga formació digital", "Efectivament: la formació és responsabilitat de l'organització, no del proveïdor."),
                    ("Emmagatzemar dades i fitxers", "Sí que ho és: és una de les funcions bàsiques."),
                    ("Executar aplicacions accessibles des de qualsevol lloc", "Sí que ho és."),
                    ("Processar grans volums de dades sota demanda", "Sí que ho és, i és un dels grans motius per a adoptar-lo."),
                ],
            ),
            ("mc",
                "Si els sensors del camp envien una lectura cada segon, què és el més raonable des del punt de vista de l'arquitectura?",
                [
                    ("Filtrar i agregar les dades en l'edge i enviar al núvol només resums i alarmes", "Correcte. Enviar-ho tot és car, lent i innecessari."),
                    ("Enviar totes les lectures al núvol sense filtrar", "És costós en dades i en diners, i sovint inútil."),
                    ("Guardar-les només en el sensor i no enviar-ne cap", "Llavors es perdria la possibilitat d'analitzar-les."),
                    ("Imprimir un informe diari amb totes les lectures", "És just el contrari de digitalitzar."),
                ],
            ),
        ],
    },
    "u06": {
        "titol": "U06. Projecte de transformació digital",
        "ra": "RA6",
        "preguntes": [
            ("mc",
                "Què significa l'acrònim OKR?",
                [
                    ("Objectius i resultats clau (Objectives and Key Results)", "Correcte. És una metodologia per a fixar metes i mesurar-ne el progrés."),
                    ("Organització, coneixement i rendiment", "No. No és el significat de l'acrònim."),
                    ("Operacions clau de referència", "No. No és el significat de l'acrònim."),
                    ("Objectius de compliment normatiu", "No. No té relació amb el compliment normatiu."),
                ],
            ),
            ("mc",
                "Quina d'aquestes formulacions és un resultat clau ben definit segons el mètode SMART?",
                [
                    ("Reduir el temps de facturació de 5 a 2 dies abans del 30 de juny", "Correcte. És específic, mesurable, assolible, rellevant i acotat en el temps."),
                    ("Millorar bastant la gestió administrativa", "No és mesurable ni està acotat en el temps."),
                    ("Ser una cooperativa més moderna", "És un desig, no un resultat clau mesurable."),
                    ("Digitalitzar-ho tot al més aviat possible", "Ni és específic ni té un termini concret."),
                ],
            ),
            ("mc",
                "Quants blocs té el model canvas i per a què serveix?",
                [
                    ("Nou blocs, i serveix per a visualitzar en una sola pàgina com funciona un model de negoci", "Correcte. Permet que tot l'equip tinga una comprensió compartida del negoci."),
                    ("Cinc blocs, i serveix per a planificar les tasques d'un projecte", "No. Ni el nombre de blocs ni la finalitat són correctes."),
                    ("Dotze blocs, i serveix per a analitzar la competència", "No. No és el model canvas."),
                    ("Quatre blocs, i serveix per a avaluar riscos", "Això s'assembla més a una matriu de riscos."),
                ],
            ),
            ("mc",
                "En una matriu de riscos, com es calcula l'impacte d'un risc?",
                [
                    ("Multiplicant la gravetat per la probabilitat", "Correcte. Amb escales d'1 a 5, l'impacte va d'1 a 25."),
                    ("Sumant la gravetat i la probabilitat", "No. La fórmula habitual és el producte, no la suma."),
                    ("Dividint el cost entre el temps de resolució", "No. No és així com es construeix la matriu."),
                    ("Comptant quantes vegades ha passat abans", "L'experiència prèvia ajuda a estimar la probabilitat, però no és el càlcul."),
                ],
            ),
            ("mc",
                "En una matriu RACI, què significa la lletra A?",
                [
                    ("Aprovador: qui té l'autoritat per a aprovar o rebutjar la faena, i només n'hi ha un", "Correcte. És un principi bàsic: una tasca, una única persona que aprova."),
                    ("Assessor: qui aporta consells durant l'execució", "Això correspondria a la C de consultat."),
                    ("Assistent: qui ajuda la persona responsable", "No forma part de l'acrònim RACI."),
                    ("Analista: qui estudia els requisits de la tasca", "No forma part de l'acrònim RACI."),
                ],
            ),
            ("mc",
                "Quina diferència hi ha entre un OKR i un KPI?",
                [
                    ("L'OKR fixa una meta ambiciosa amb resultats mesurables; el KPI mesura el rendiment habitual", "Correcte. L'OKR motiva i canvia cada cicle; el KPI vigila i es manté estable."),
                    ("Són exactament el mateix", "No. Tenen finalitats diferents i conviuen."),
                    ("L'OKR és quantitatiu i el KPI sempre és qualitatiu", "No. Precisament els resultats clau dels OKR han de ser quantificables."),
                    ("El KPI només l'utilitzen les empreses grans", "No és cert."),
                ],
            ),
            ("mc",
                "Quina metodologia de gestió de projectes utilitza sprints curts i revisions periòdiques amb l'equip?",
                [
                    ("Scrum", "Correcte. És una metodologia àgil basada en cicles curts i millora contínua."),
                    ("Kanban", "Kanban és àgil i visual, però no es basa en sprints amb data fixa."),
                    ("Cascada (waterfall)", "No. La cascada és seqüencial i poc flexible."),
                    ("Lean startup", "Se centra a eliminar malbaratament i validar hipòtesis, no en sprints."),
                ],
            ),
            ("mc",
                "Per què és imprescindible la gestió del canvi en un projecte de transformació digital?",
                [
                    ("Perquè la major part dels fracassos venen de les persones, no de la tecnologia", "Correcte. Sense formació, comunicació i implicació, el millor sistema acaba sense fer-se servir."),
                    ("Perquè ho exigeix la normativa europea", "No existeix cap obligació legal d'aquest tipus."),
                    ("Perquè permet reduir el pressupost del projecte", "No és la seua finalitat."),
                    ("Perquè substitueix la necessitat de fer formació", "Al contrari: la formació n'és una part central."),
                ],
            ),
            ("mc",
                "En el projecte de Tarongina, l'encarregat del magatzem es nega a fer servir la tauleta nova i continua apuntant en paper. Què cal activar?",
                [
                    ("Gestió del canvi: entendre'n el motiu, formar-lo i implicar-lo en la solució", "Correcte. La resistència al canvi es gestiona escoltant i acompanyant, no imposant."),
                    ("Substituir la persona per una altra amb més nivell digital", "No és la primera resposta raonable ni la més efectiva."),
                    ("Retirar la tauleta i tornar al paper", "Seria renunciar al projecte sense analitzar-ne la causa."),
                    ("Augmentar el pressupost en tecnologia", "Més tecnologia no resol un problema d'adopció."),
                ],
            ),
            ("mc",
                "Quina és la primera fase en la gestió d'un projecte?",
                [
                    ("La iniciació: definir el problema a resoldre i els objectius", "Correcte. Sense un problema ben definit, la resta del projecte va a cegues."),
                    ("L'execució de les tasques planificades", "No. L'execució arriba després de la planificació."),
                    ("El tancament i les lliçons apreses", "No. És l'última fase."),
                    ("La monitorització i el control", "No. Acompanya l'execució, però no és la primera fase."),
                ],
            ),
        ],
    },
}
